### Spring profiles

---
spring:
  profiles: default
  jpa:
    show-sql: true
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS OSASE
    driverClassName: org.h2.Driver
    username: sa
    password:

  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ENC(URGhHFt19WL1ud3YHfYv+O24FAVSfLXZ/cdDvqhQZulnVju3jXRU+w==)
    password: ENC(7gGye7LO5pLAeOYhIv0zc+TVe1ZRcjuT)
    properties:
      mail:
        smtp:
          starttls:
            enable: true

hibernate:
  hbm2ddl:
    auto: update

logging:
  level:
    org:
      hibernate:
        SQL: info

stormpath:
#  enabled: false
  application:
    href: 'https://api.stormpath.com/v1/applications/2juRGQtx3QKVxqPNjQXsWi'
  authorized:
    admin:
      group:
        href: 'https://api.stormpath.com/v1/groups/1gMB5FZx2cITN4MPBVAtFB'
    user:
      group:
        href: 'https://api.stormpath.com/v1/groups/2nlGvUv0hWZohBdL0xoFrN'

---